apiVersion: v1
kind: Pod
metadata:
  name: hacker
  labels:
    group: rkalyana-public
    app: arpspoof
spec:
  containers:
  - name: hacker
    image: rkalyana/hacker-notebook
    ports:
    - containerPort: 8888
