apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    group: rkalyana
    app: arpspoof-server
spec:
  containers:
  - name: server
    image: timwang/ieeetrycybserverapacheflaskappsslnohstsnorewrite:1.0
    ports:
    - containerPort: 80
    - containerPort: 443
