apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    group: rkalyana
    app: arpspoof
spec:
  containers:
  - name: server
    image: timwang/ieeetrycybserverapacheflaskappsslhstsrewrite:4.0
    ports:
    - containerPort: 80
    - containerPort: 443
