apiVersion: v1
kind: Pod
metadata:
  name: victim
  labels:
    group: rkalyana-public
    app: arpspoof-victim
spec:
  containers:
  - name: victim
    image: rkalyana/ubuntu-xfce-vnc
    ports:
    - containerPort: 6901
    - containerPort: 5901
