kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-arpspoof
spec:
  podSelector:
    matchLabels:
      group: rkalyana
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: group, operator: In, values: [rkalyana,rkalyana-public]}
